version: "3.8"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
  mongodb:
    container_name: mongodb
    ports:
      - "27017:27017"
    image: mongo:latest
    environment:
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"

volumes:
  cache: driver:local
  mongodb-data: {}
